"""create security events table

Revision ID: 7ac2f3b51ce7
Revises: 
Create Date: 2026-08-07 20:06:58.563689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7ac2f3b51ce7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('http_method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_event_type', 'security_events', ['event_type'], unique=False)
    op.create_index('ix_security_events_source_ip', 'security_events', ['source_ip'], unique=False)
    op.create_index('ix_security_events_timestamp', 'security_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_events_timestamp', table_name='security_events')
    op.drop_index('ix_security_events_source_ip', table_name='security_events')
    op.drop_index('ix_security_events_event_type', table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
