"""create attack sessions

Revision ID: 7e0cf8a24e75
Revises: 7ac2f3b51ce7
Create Date: 2026-08-10 20:24:38.316549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7e0cf8a24e75'
down_revision: Union[str, Sequence[str], None] = '7ac2f3b51ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attack_sessions_last_seen', 'attack_sessions', ['last_seen'], unique=False)
    op.create_index('ix_attack_sessions_source_ip', 'attack_sessions', ['source_ip'], unique=False)
    op.add_column('security_events', sa.Column('session_id', sa.UUID(), nullable=False))
    op.create_index('ix_security_events_session_id', 'security_events', ['session_id'], unique=False)
    op.create_foreign_key(None, 'security_events', 'attack_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'security_events', type_='foreignkey')
    op.drop_index('ix_security_events_session_id', table_name='security_events')
    op.drop_column('security_events', 'session_id')
    op.drop_index('ix_attack_sessions_source_ip', table_name='attack_sessions')
    op.drop_index('ix_attack_sessions_last_seen', table_name='attack_sessions')
    op.drop_table('attack_sessions')
    # ### end Alembic commands ###
