"""add severity and score to attack sessions

Revision ID: 8496817b511a
Revises: 7e0cf8a24e75
Create Date: 2026-08-11 12:11:32.402575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8496817b511a'
down_revision: Union[str, Sequence[str], None] = '7e0cf8a24e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "attack_sessions",
        sa.Column(
            "severity",
            sa.String(length=16),
            nullable=False,
            server_default="low",
        ),
    )

    op.add_column(
        "attack_sessions",
        sa.Column(
            "score",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column(
        "attack_sessions",
        "severity",
        server_default=None,
    )

    op.alter_column(
        "attack_sessions",
        "score",
        server_default=None,
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attack_sessions', 'score')
    op.drop_column('attack_sessions', 'severity')
    # ### end Alembic commands ###
